### ISSUE TITLE
Not working in astro files

### ISSUE THREAD

**Issue by bushblade** [leafOfTree/vim-matchtag#11]
This doesn't seem to work in astro files.
I have in my Neovim config
```lua
      vim.g.vim_matchtag_files = "*.astro,*.html,*.xml,*.js,*.jsx,*.vue,*.svelte,*.jsp,*.tsx"
```
All the other file types in that string work with matchtag except astro.

**Comment by leafOfTree** [comment]
hi, sorry for the late reply.

I tried with neovim and it works for me. Do you have other plugins enabled for astro files?
Just as you know, this plugin only provides tag highlights. You may check `:h matchit` for jumping between tags.

![Screenshot 2024-10-18 at 16 54 51](https://github.com/user-attachments/assets/4013d6d0-0c05-4af9-baf4-a6d604fa4980)

config: 
```vim
let g:vim_matchtag_files = '*.html,*.xml,*.js,*.jsx,*.ts,*.tsx,*.vue,*.svelte,*.jsp,*.php,*.erb,*.md,*.wxml,*.markdown,*.astro'
```
astro syntax plugin: https://github.com/wuelnerdotexe/vim-astro

**Comment by bushblade** [comment]
Hi and thanks for the reply.
No I just have treesitter and lsp set up for Astro, nothing else.

![Screenshot from 2024-10-18 10-18-39](https://github.com/user-attachments/assets/855ec80c-8d9d-4318-aa70-fae00985097c)
And here is my current config using Lazy:

```lua
return {
  {
    "leafOfTree/vim-matchtag",
    config = function()
      vim.g.vim_matchtag_files = "*.astro,*.html,*.xml,*.js,*.jsx,*.vue,*.svelte,*.jsp,*.tsx"
    end,
  },
}
```

**Comment by leafOfTree** [comment]
hi, `init` works here instead of `config` to set `vim.g.*` configuration, according to lazy.nvim doc: https://lazy.folke.io/spec#spec-setup

```vim
return {
  {
    "leafOfTree/vim-matchtag",
    init = function()
      vim.g.vim_matchtag_files = "*.astro,*.html,*.xml,*.js,*.jsx,*.vue,*.svelte,*.jsp,*.tsx"
    end,
  },
}
```

**Comment by leafOfTree** [comment]
I've just added astro to the default enabled files, so actually you don't have to add `config` or `init` with the latest version.

**Comment by bushblade** [comment]
Thank you! Yes that indeed solves it.
