### ISSUE TITLE
maping defaul bind

### ISSUE THREAD

**Issue by timsofteng** [leafOfTree/vim-matchtag#5]
Hello. I suppose matchtag tries to remap some default binding. Maybe it is ctrl-b. Could you please change map from ctrl-b to something availiable?

**Comment by leafOfTree** [comment]
Hi, thank you for the feedback. I agree it's better to leave the options to unbind as default. `<c-t>` and `<c-b>` were used and they are free now.
||||
-- | -- | --
g:vim_matchtag_mapping_toggle | Key mapping to toggle highlighting. | ''
g:vim_matchtag_mapping_both | Key mapping to toggle both at runtim. | ''

**Comment by leafOfTree** [comment]
Hi, timsofteng. I'll close it. Please let me know if any problems.
