### ISSUE TITLE
Not working in js and jsx files

### ISSUE THREAD

**Issue by bushblade** [leafOfTree/vim-matchtag#6]
Hi I have this working in .html files but it's not working in .js and .jsx files.
I have in my config

```lua
vim.g.vim_matchtag_enable_by_default = 1
vim.g.vim_matchtag_files = "*.html,*.xml,*.js,*.jsx,*.vue,*.svelte,*.jsp,*.tsx"
vim.g.vim_matchtag_highlight_cursor_on = 1
```
Works for me in html

![Screenshot_2021-08-21_12-46-16](https://user-images.githubusercontent.com/21976188/130320711-bb96bf46-a7b9-4c1d-a745-bd31eee86a44.png)

But not in jsx or js
![Screenshot_2021-08-21_12-47-11](https://user-images.githubusercontent.com/21976188/130320727-60736a18-9ad9-425f-b56e-8f5b66db11b9.png)

I'm probably missing something obvious but could do with some pointers as to what that is, thanks.

**Comment by leafOfTree** [comment]
Hi, thanks for the feedback. The config looks good. It seems to be lua config for nvim. 

Can you please try the two ways below and share the output with me to help debug?

1. You can enable the debug messages by
    ```lua
    vim.g.vim_matchtag_debug = 1
    ```
    Then move the cursor around and see what messages say.

2. You can also run below in vim
    ```
    echo map(synstack(line('.'), col('.')), { _, id -> synIDattr(id, 'name') })
    ```
    to see the whole syntax under the cursor.

**Comment by leafOfTree** [comment]
I was also wondering which js/jsx plugin you use? Maybe I can try to reproduce it.

**Comment by bushblade** [comment]
Hi @leafOfTree , thanks for looking into this.
I added that option for debug messages and in a .js file I get..
![Screenshot_2021-08-23_08-14-16](https://user-images.githubusercontent.com/21976188/130405979-c00213ab-cadb-4c41-a164-4be314b9ff06.png)
In html I get..
![Screenshot_2021-08-23_08-16-02](https://user-images.githubusercontent.com/21976188/130406115-fea98efb-dfc0-4bbe-99b5-95fa0bfb3b8d.png)
And jsx is the same as js.
I'm using treesitter and lsp only for js/jsx.
[You can see my config here if that helps.](https://github.com/bushblade/nvim)

**Comment by leafOfTree** [comment]
Hi, @bushblade Thanks for sharing. I tried your config, where I found the treesitter and packer are really incredible already.

It turns out that this plugin skips the syntax as treesitter handles syntax differently from common vim way. 

I made a change https://github.com/leafOfTree/vim-matchtag/commit/115e30b08fbc4990cd66953e03178d5ac7984239 to support it. Please update this plugin to see if it works for you.
<img width="448" alt="Screen Shot 2021-08-23 at 7 25 06 PM" src="https://user-images.githubusercontent.com/13349592/130439682-aeee94d6-d81f-4858-bd19-566d0bacd20c.png">

**Comment by bushblade** [comment]
@leafOfTree That's great, thank you so much. Yes I can confirm that fixes it for me...
![Screenshot_2021-08-23_13-06-42](https://user-images.githubusercontent.com/21976188/130444484-37e91f79-6868-4f74-bb60-75adaa881bad.png)
