### ISSUE TITLE
 vim-matchtag only work one file in the project

### ISSUE THREAD

**Issue by frankykong** [leafOfTree/vim-matchtag#7]
I am working in the same project. as you can see Course.js file can hight the matched tages, but Login.js can't. the other file don't work either. Can some one tell me what is going on? thank you.

![image](https://user-images.githubusercontent.com/10731074/157900209-f97fa8c0-0df1-4d54-af21-537d07ab2c80.png)
![image](https://user-images.githubusercontent.com/10731074/157900491-39d6de6b-cacb-41be-8b0b-784ea48305f2.png)

**Comment by leafOfTree** [comment]
Hi, there. Thanks for the feedback.
Could you share a simple demo that doesn't work for me to reproduce the issue? 

For example, some code snippets like 

```jsx
function () {
  return (
    <TouchableOpacity>
      <Text style={styles.buttonTextStyle}>LOGIN</Text>
    </TouchableOpacity>
  )
}
```

**Comment by frankykong** [comment]
Hi, there. Thank you for reply. 

Since this week I had worked on my project with this setting. I found out some time it show up, mostly it didn't.
So I was wondering maybe it's some kind of "refreshing" issure. Then i change set timeoutlen=100 to 500, and it works!

**Comment by leafOfTree** [comment]
Glad to hear that! I didn't know `timeoutlen` before.
